# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Neuro_Linear <- function(y, X, N, BURN, alpha, w, sig, n1, p1, eta, alpha0, size_a, type, eta_update, alpha0_update, sig_update, K, B_size, a0, b0, prior_sig_type, verbose) {
    .Call(`_NPrior_Neuro_Linear`, y, X, N, BURN, alpha, w, sig, n1, p1, eta, alpha0, size_a, type, eta_update, alpha0_update, sig_update, K, B_size, a0, b0, prior_sig_type, verbose)
}

Neuro_ReLU_Linear <- function(y, X, N, BURN, alpha, w, sig, n1, p1, eta, alpha0, a0, b0, alpha0_update, eta_update, sig_update, B_size, prior_sig_type, verbose) {
    .Call(`_NPrior_Neuro_ReLU_Linear`, y, X, N, BURN, alpha, w, sig, n1, p1, eta, alpha0, a0, b0, alpha0_update, eta_update, sig_update, B_size, prior_sig_type, verbose)
}

